# Generated by Django 6.1 on 2026-08-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_playlist_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_covers/'),
        ),
    ]
